1-hello-world : 1-hello-world.cpp
	g++ -fopenmp -std=c++17 -o 1-hello-world 1-hello-world.cpp

2-vector-sum : 2-vector-sum.cpp
	g++ -fopenmp -std=c++17 -o 2-vector-sum 2-vector-sum.cpp

3-parallel-for : 3-parallel-for.cpp
	g++ -fopenmp -std=c++17 -o 3-parallel-for 3-parallel-for.cpp

clean:
	rm -v 1-hello-world 2-vector-sum 3-parallel-for
